name: flagkit
description: FlagKit is a collection of all country flags for flutter for easier integration.
version: 0.0.1
homepage: https://github.com/MezzLasha/flagkit_flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/flags/